add usage in README

diff --git a/bili2any b/bili2any
--- a/bili2any
+++ b/bili2any
@@ -1,4 +1,16 @@
 cid=`curl --compressed $1 | grep -oP "(?<=EmbedPlayer\(\'player\', \"http://static.hdslb.com/play.swf\", \"cid=)[0-9]+(?=&)"`
+
+if [ -z "$cid" ] 
+then
+cid=`curl --compressed $1 | grep -oP "(?<=cid=)[0-9]+(?=&)"`
+fi
+
+if [ -z "$cid" ] 
+then
+echo "error cid got!"
+exit 1
+fi
+
 curl --compressed "http://comment.bilibili.com/"$cid".xml" > /tmp/$cid.xml
 
 
@@ -25,5 +37,9 @@ echo $assname
 ./danmaku2ass/danmaku2ass.py -o /tmp/$assname -s 1920x1080 -fs 48 -a 0.8 -dm 13 -ds 5 /tmp/$cid.xml
 
 echo $vediourl
-#wget $vediourl
-vlc --sub-file /tmp/$assname $vediourl
+
+vlc --sub-file /tmp/$assname "$vediourl"
+
+#wget -O /tmp/$cid.vedio $vediourl &
+#sleep 5
+#vlc --sub-file /tmp/$assname /tmp/$cid.vedio
